create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  username text not null unique,
  display_name text not null default '',
  avatar_url text not null default '',
  bio text not null default '',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.recently_played (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  track_id text not null,
  release_id text not null default '',
  title text not null,
  artist text not null,
  album text not null,
  cover_url text not null default '',
  played_at timestamptz not null default now(),
  unique (user_id, track_id)
);

create table if not exists public.playlists (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  description text not null default '',
  is_public boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.playlist_items (
  id bigint generated by default as identity primary key,
  playlist_id uuid not null references public.playlists(id) on delete cascade,
  track_id text not null,
  release_id text not null default '',
  title text not null,
  artist text not null,
  album text not null,
  cover_url text not null default '',
  position integer not null default 0,
  added_at timestamptz not null default now()
);

create or replace function public.touch_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

drop trigger if exists profiles_touch_updated_at on public.profiles;
create trigger profiles_touch_updated_at
before update on public.profiles
for each row execute procedure public.touch_updated_at();

drop trigger if exists playlists_touch_updated_at on public.playlists;
create trigger playlists_touch_updated_at
before update on public.playlists
for each row execute procedure public.touch_updated_at();

alter table public.profiles enable row level security;
alter table public.recently_played enable row level security;
alter table public.playlists enable row level security;
alter table public.playlist_items enable row level security;

drop policy if exists "profiles_select_public" on public.profiles;
create policy "profiles_select_public"
on public.profiles for select
using (true);

drop policy if exists "profiles_insert_self" on public.profiles;
create policy "profiles_insert_self"
on public.profiles for insert
with check (auth.uid() = id);

drop policy if exists "profiles_update_self" on public.profiles;
create policy "profiles_update_self"
on public.profiles for update
using (auth.uid() = id)
with check (auth.uid() = id);

drop policy if exists "recently_played_owner_select" on public.recently_played;
create policy "recently_played_owner_select"
on public.recently_played for select
using (auth.uid() = user_id);

drop policy if exists "recently_played_owner_write" on public.recently_played;
create policy "recently_played_owner_write"
on public.recently_played for all
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "playlists_public_or_owner_select" on public.playlists;
create policy "playlists_public_or_owner_select"
on public.playlists for select
using (is_public or auth.uid() = user_id);

drop policy if exists "playlists_owner_insert" on public.playlists;
create policy "playlists_owner_insert"
on public.playlists for insert
with check (auth.uid() = user_id);

drop policy if exists "playlists_owner_update" on public.playlists;
create policy "playlists_owner_update"
on public.playlists for update
using (auth.uid() = user_id)
with check (auth.uid() = user_id);

drop policy if exists "playlists_owner_delete" on public.playlists;
create policy "playlists_owner_delete"
on public.playlists for delete
using (auth.uid() = user_id);

drop policy if exists "playlist_items_public_or_owner_select" on public.playlist_items;
create policy "playlist_items_public_or_owner_select"
on public.playlist_items for select
using (
  exists (
    select 1
    from public.playlists
    where playlists.id = playlist_items.playlist_id
      and (playlists.is_public or playlists.user_id = auth.uid())
  )
);

drop policy if exists "playlist_items_owner_insert" on public.playlist_items;
create policy "playlist_items_owner_insert"
on public.playlist_items for insert
with check (
  exists (
    select 1
    from public.playlists
    where playlists.id = playlist_items.playlist_id
      and playlists.user_id = auth.uid()
  )
);

drop policy if exists "playlist_items_owner_update" on public.playlist_items;
create policy "playlist_items_owner_update"
on public.playlist_items for update
using (
  exists (
    select 1
    from public.playlists
    where playlists.id = playlist_items.playlist_id
      and playlists.user_id = auth.uid()
  )
)
with check (
  exists (
    select 1
    from public.playlists
    where playlists.id = playlist_items.playlist_id
      and playlists.user_id = auth.uid()
  )
);

drop policy if exists "playlist_items_owner_delete" on public.playlist_items;
create policy "playlist_items_owner_delete"
on public.playlist_items for delete
using (
  exists (
    select 1
    from public.playlists
    where playlists.id = playlist_items.playlist_id
      and playlists.user_id = auth.uid()
  )
);
